// Mocks generated by Mockito 5.4.6 from annotations
// in codeflutter/test/ranking_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i8;

import 'package:codeflutter/dto/LoginResponse.dart' as _i3;
import 'package:codeflutter/dto/RegisterResponse.dart' as _i2;
import 'package:codeflutter/network/api_service.dart' as _i5;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponse_0 extends _i1.SmartFake
    implements _i2.RegisterResponse {
  _FakeRegisterResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> checkUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#checkUsername, [username]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.RegisterResponse> register({
    required String? username,
    required String? password,
    required String? nickname,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #password: password,
              #nickname: nickname,
            }),
            returnValue: _i6.Future<_i2.RegisterResponse>.value(
              _FakeRegisterResponse_0(
                this,
                Invocation.method(#register, [], {
                  #username: username,
                  #password: password,
                  #nickname: nickname,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.RegisterResponse>);

  @override
  _i6.Future<_i3.LoginResponse> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i6.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i6.Future<_i3.LoginResponse>);

  @override
  _i6.Future<bool> reissueTokens() =>
      (super.noSuchMethod(
            Invocation.method(#reissueTokens, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>> getRankings() =>
      (super.noSuchMethod(
            Invocation.method(#getRankings, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getProgressInfo(
    int? userId,
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressInfo, [userId, latitude, longitude]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  String getContentType(String? extension) =>
      (super.noSuchMethod(
            Invocation.method(#getContentType, [extension]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getContentType, [extension]),
            ),
          )
          as String);

  @override
  _i6.Future<Map<String, dynamic>> uploadImage(_i8.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [image]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> submitQuestWithImages(
    String? landmarkName,
    String? stdUrl,
    String? clientUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitQuestWithImages, [
              landmarkName,
              stdUrl,
              clientUrl,
            ]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i4.Response> authenticatedRequest(
    String? method,
    String? path, {
    Map<String, String>? headers,
    Object? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #authenticatedRequest,
              [method, path],
              {#headers: headers, #body: body},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #authenticatedRequest,
                  [method, path],
                  {#headers: headers, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);
}
